# Generated by Django 2.2.9 on 2021-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя сдавшего')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия сдавшего')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('result', models.IntegerField(verbose_name='Сумма баллов')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=30, verbose_name='Вопрос')),
                ('key_type', models.CharField(choices=[('1', '1-0'), ('2', '0-1'), ('3', '0-2-3'), ('4', '3-2-0')], max_length=1)),
            ],
        ),
    ]
