# Generated by Django 2.2.9 on 2021-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_tests', '0002_auto_20210530_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма баллов'),
        ),
    ]
